name: Reusable Build & Test

on:
  workflow_call:
    inputs:
      java_version:
        type: string
        required: false
        default: "17"
      run_checkstyle:
        type: boolean
        required: false
        default: true
      # Optional: override CVSS fail threshold (default 7.0)
      dependency_check_fail_on_cvss:
        type: string
        required: false
        default: "7.0"
    secrets:
      METOFFICE_API_KEY:
        required: false

jobs:
  build:
    name: Build, Checkstyle, Dependency Check & Test
    runs-on: ubuntu-latest
    env:
      METOFFICE_API_KEY: ${{ secrets.METOFFICE_API_KEY || 'DUMMY' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ inputs.java_version }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ inputs.java_version }}

      - name: Cache Maven repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: m2-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            m2-${{ runner.os }}-

      - name: Build & unit tests
        run: mvn -B -q clean verify

      - name: Run Checkstyle (report + fail on violations)
        if: ${{ inputs.run_checkstyle }}
        run: |
          mvn -B -q \
            -Dcheckstyle.consoleOutput=true \
            -Dcheckstyle.failOnViolation=true \
            checkstyle:checkstyle checkstyle:check || EXIT=$?
          # Don't mask the XML/HTML report by failing early; preserve exit code for later
          echo "CHECKSTYLE_EXIT=${EXIT:-0}" >> $GITHUB_ENV

      - name: OWASP Dependency-Check (aggregate report)
        run: |
          mvn -B -q \
            org.owasp:dependency-check-maven:aggregate \
            -Dformat=HTML,XML,JSON \
            -DfailOnCVSS=${{ inputs.dependency_check_fail_on_cvss }} || EXIT=$?
          echo "DC_EXIT=${EXIT:-0}" >> $GITHUB_ENV

      # --- Collect reports as artifacts ---

      - name: Gather report paths
        id: paths
        run: |
          echo "checkstyle_xml=$(ls -1 **/target/checkstyle-result.xml 2>/dev/null || true)" >> $GITHUB_OUTPUT
          echo "checkstyle_html=$(ls -1 **/target/site/checkstyle.html 2>/dev/null || true)" >> $GITHUB_OUTPUT
          echo "dc_html=$(ls -1 **/target/dependency-check-report.html **/target/site/dependency-check.html 2>/dev/null || true)" >> $GITHUB_OUTPUT
          echo "dc_xml=$(ls -1 **/target/dependency-check-report.xml 2>/dev/null || true)" >> $GITHUB_OUTPUT
          echo "dc_json=$(ls -1 **/target/dependency-check-report.json 2>/dev/null || true)" >> $GITHUB_OUTPUT

      - name: Upload Dependency-Check reports
        if: ${{ steps.paths.outputs.dc_html || steps.paths.outputs.dc_xml || steps.paths.outputs.dc_json }}
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-reports
          if-no-files-found: ignore
          path: |
            **/target/dependency-check-report.html
            **/target/site/dependency-check.html
            **/target/dependency-check-report.xml
            **/target/dependency-check-report.json

      - name: Upload Checkstyle reports
        if: ${{ inputs.run_checkstyle && (steps.paths.outputs.checkstyle_xml || steps.paths.outputs.checkstyle_html) }}
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-reports
          if-no-files-found: ignore
          path: |
            **/target/checkstyle-result.xml
            **/target/site/checkstyle.html

      - name: Upload test reports (Surefire/Failsafe)
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          if-no-files-found: ignore
          path: |
            **/target/surefire-reports/**
            **/target/failsafe-reports/**

      # --- Fail the job if either Checkstyle or Dependency-Check failed ---

      - name: Fail on Checkstyle or Dependency-Check errors
        run: |
          CS=${CHECKSTYLE_EXIT:-0}
          DC=${DC_EXIT:-0}
          if [ "$CS" -ne 0 ] || [ "$DC" -ne 0 ]; then
            echo "Checkstyle exit: $CS, Dependency-Check exit: $DC"
            exit 1
          fi
