name: CD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-test:
    uses: ./.github/workflows/_build-test.yml
    with:
      java_version: "17"
      run_checkstyle: false   # e.g., skip here if you want
    secrets: inherit

  publish:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # ... your version bump / deploy / release steps here ...
