name: CD (Maven library auto-version)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      OWNER: ${{ github.repository_owner }}
      REPO:  ${{ github.event.repository.name }}
      METOFFICE_API_KEY: DUMMY

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # we will create tags

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Determine versions
        id: ver
        shell: bash
        run: |
          set -euo pipefail
          CURR=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.version)
          # release = strip -SNAPSHOT if present
          REL="${CURR/-SNAPSHOT/}"
          # function: bump patch of x.y.z
          bump_patch () {
            IFS='.' read -r MA MI PA <<<"$1"
            echo "${MA}.${MI}.$((PA+1))"
          }
          # NEXT snapshot after release
          if [[ "$REL" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            NEXT="$(bump_patch "$REL")-SNAPSHOT"
          else
            echo "Version must be x.y.z (optionally -SNAPSHOT). Got: $CURR"
            exit 1
          fi

          echo "current=$CURR"           >> $GITHUB_OUTPUT
          echo "release=$REL"            >> $GITHUB_OUTPUT
          echo "next_snapshot=$NEXT"     >> $GITHUB_OUTPUT

      - name: Set release version in pom.xml
        run: mvn -B -ntp versions:set -DnewVersion=${{ steps.ver.outputs.release }} versions:commit

      - name: Build & test (release)
        run: mvn -B -ntp verify

      - name: Publish to GitHub Packages (Maven)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn -B -ntp -DskipTests=true \
            -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${OWNER}/${REPO} \
            deploy

      - name: Collect release assets
        run: |
          mkdir -p release-assets
          cp target/*.jar release-assets/ || true

      - name: Tag release
        id: tag
        run: |
          TAG="v${{ steps.ver.outputs.release }}"
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: Release ${{ steps.tag.outputs.tag }}
          generate_release_notes: true
          files: |
            release-assets/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump to next SNAPSHOT and push
        run: |
          mvn -B -ntp versions:set -DnewVersion=${{ steps.ver.outputs.next_snapshot }} versions:commit
          git add pom.xml
          git commit -m "chore(release): bump to ${{ steps.ver.outputs.next_snapshot }}"
          git push
