# .github/workflows/ci.yml
name: Java CI

on:
  pull_request:
    branches-ignore:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  codeql:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: java
      - uses: github/codeql-action/autobuild@v3
      - uses: github/codeql-action/analyze@v3

  tests:
    name: Tests on JDK ${{ matrix.java_version }}
    strategy:
      matrix:
        java_version: [17, 21, 24]
    uses: ./.github/workflows/_tests.yml
    with:
      java_version: ${{ matrix.java_version }}
    secrets: inherit

  static-checks:
    name: Static checks (Checkstyle on JDK 21)
    uses: ./.github/workflows/_static-checks.yml
    with:
      java_version: "21"
    secrets: inherit

  dependency-review:
    name: Dependency Review (PR diff)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Dependency review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high          # block High/Critical by default
          comment-summary-in-pr: true
          # Optional knobs:
          # deny-licenses: "AGPL-3.0"     # comma-separated list
          # allow-ghsas: "GHSA-xxxx,GHSA-yyyy"
