name: Java CI

on:
  pull_request:
    branches-ignore:
      - master

jobs:
  codeql:
    name: CodeQL Code Scanning
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with:
          languages: java
      - uses: github/codeql-action/autobuild@v3
      - uses: github/codeql-action/analyze@v3

  tests:
    name: Tests on JDK ${{ matrix.java_version }}
    strategy:
      matrix:
        java_version: [17, 21, 24]
    uses: ./.github/workflows/_tests.yml
    with:
      java_version: ${{ matrix.java_version }}
    secrets: inherit

  static-checks:
    name: Static checks (JDK 21)
    uses: ./.github/workflows/_static-checks.yml
    with:
      java_version: "21"
      dependency_check_fail_on_cvss: "7.0"
    secrets: inherit
